[package]
name = "interpreter-starter-rust"
version = "0.1.0"
authors = ["Bohdan Ohorodnii <limposfeed@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.68"
bytes = "1.3.0"
thiserror = "1.0.38"
colored = "2.0"